/* eslint-disable react/prop-types */
import * as React from 'react';
import { styled } from '@mui/material/styles';
import { AppBar as MuiAppBar, Badge, IconButton, Toolbar, Typography, Popover } from '@mui/material';
import { Info as InfoIcon, Menu as MenuIcon } from '@mui/icons-material';
import OffCanvas from "./Offcanvas.jsx";
import logoImage from "../assets/images/logo-v.png";

//MUI styling
const drawerWidth = 230;

const AppBar = styled(MuiAppBar, {
  shouldForwardProp: (prop) => prop !== 'open',
})(({ theme, open }) => ({
  zIndex: theme.zIndex.drawer + 1,
  transition: theme.transitions.create(['width', 'margin'], {
    easing: theme.transitions.easing.sharp,
    duration: theme.transitions.duration.leavingScreen,
  }),
  ...(open && {
    marginLeft: drawerWidth,
    width: `calc(100% - ${drawerWidth}px)`,
    transition: theme.transitions.create(['width', 'margin'], {
      easing: theme.transitions.easing.sharp,
      duration: theme.transitions.duration.enteringScreen,
    }),
  }),
}));



function AppHeader({ open, toggleDrawer, cartBadgeNumber, gamesInCart, handleDelete }) {
  const [anchorEl, setAnchorEl] = React.useState(null);

  const handleClick = (event) => {
    setAnchorEl(event.currentTarget);
  };

  const handleClose = () => {
    setAnchorEl(null);
  };

  const openPopOver = Boolean(anchorEl);
  const id = openPopOver ? 'info-popover' : undefined;

  return (
    <AppBar position="absolute" open={open}>
      <Toolbar
        className='toolBar'
        sx={{
          pr: '24px', // keep right padding when drawer closed
        }}
      >
        <IconButton
          edge="start"
          color="inherit"
          aria-label="open drawer"
          onClick={toggleDrawer}
          sx={{
            marginRight: '36px',
            ...(open && { display: 'none' }),
          }}
        >
          <MenuIcon />
        </IconButton>

        <Typography
          component="h1"
          variant="h6"
          color="inherit"
          noWrap
          sx={{ flexGrow: 1 }}
        >
          <img className='dashBoardLogoImg' src={logoImage} alt="" />
          Vapor: The Ultimate Game Store
          
          <InfoIcon className="infoIcon" aria-describedby={id} variant="contained" onClick={handleClick}/>
          
          <Popover
            id={id}
            open={openPopOver}
            anchorEl={anchorEl}
            onClose={handleClose}
            anchorOrigin={{
              vertical: 'bottom',
              horizontal: 'left',
            }}
          >
            <p className='popOverText'>This website is not a real game store and games on this website can not be purchased. Prices do not reflect their real retail prices, they are generated by an algorithm. On each game's page, however, are links to store pages where games can be purchased. At this stage, this project serves as a visual database for games and a convenient way to reach their store links.</p>
          </Popover>
        </Typography>
        
        <Badge className="offCanvasBadge" badgeContent={cartBadgeNumber} color="secondary">
          <OffCanvas 
            gamesInCart={gamesInCart}
            handleDelete={handleDelete}
          />
        </Badge>
      </Toolbar>
    </AppBar>
  );
}

export default AppHeader;